import type { Metadata } from "next";

import "./globals.css";
import Layout from "../component/layout";
import { Provider } from "../components/ui/provider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
    
        <Provider>
          <Layout>
          {children}
          </Layout>

</Provider>
      
       
        
      </body>
    </html>
  );
}
